# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Link(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _class: List[str]=None, title: str=None, rel: List[str]=None, href: str=None, type: str=None):  # noqa: E501
        """Link - a model defined in Swagger

        :param _class: The _class of this Link.  # noqa: E501
        :type _class: List[str]
        :param title: The title of this Link.  # noqa: E501
        :type title: str
        :param rel: The rel of this Link.  # noqa: E501
        :type rel: List[str]
        :param href: The href of this Link.  # noqa: E501
        :type href: str
        :param type: The type of this Link.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            '_class': List[str],
            'title': str,
            'rel': List[str],
            'href': str,
            'type': str
        }

        self.attribute_map = {
            '_class': 'class',
            'title': 'title',
            'rel': 'rel',
            'href': 'href',
            'type': 'type'
        }
        self.__class = _class
        self._title = title
        self._rel = rel
        self._href = href
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Link':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Link of this Link.  # noqa: E501
        :rtype: Link
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _class(self) -> List[str]:
        """Gets the _class of this Link.


        :return: The _class of this Link.
        :rtype: List[str]
        """
        return self.__class

    @_class.setter
    def _class(self, _class: List[str]):
        """Sets the _class of this Link.


        :param _class: The _class of this Link.
        :type _class: List[str]
        """

        self.__class = _class

    @property
    def title(self) -> str:
        """Gets the title of this Link.


        :return: The title of this Link.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Link.


        :param title: The title of this Link.
        :type title: str
        """

        self._title = title

    @property
    def rel(self) -> List[str]:
        """Gets the rel of this Link.


        :return: The rel of this Link.
        :rtype: List[str]
        """
        return self._rel

    @rel.setter
    def rel(self, rel: List[str]):
        """Sets the rel of this Link.


        :param rel: The rel of this Link.
        :type rel: List[str]
        """
        if rel is None:
            raise ValueError("Invalid value for `rel`, must not be `None`")  # noqa: E501

        self._rel = rel

    @property
    def href(self) -> str:
        """Gets the href of this Link.


        :return: The href of this Link.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this Link.


        :param href: The href of this Link.
        :type href: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    @property
    def type(self) -> str:
        """Gets the type of this Link.


        :return: The type of this Link.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Link.


        :param type: The type of this Link.
        :type type: str
        """

        self._type = type
