# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.action import Action  # noqa: F401,E501
from swagger_server.models.entity import Entity  # noqa: F401,E501
from swagger_server.models.link import Link  # noqa: F401,E501
from swagger_server.models.matter_properties import MatterProperties  # noqa: F401,E501
from swagger_server import util


class MatterResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _class: List[str]=None, actions: List[Action]=None, links: List[Link]=None, properties: MatterProperties=None):  # noqa: E501
        """MatterResponse - a model defined in Swagger

        :param _class: The _class of this MatterResponse.  # noqa: E501
        :type _class: List[str]
        :param actions: The actions of this MatterResponse.  # noqa: E501
        :type actions: List[Action]
        :param links: The links of this MatterResponse.  # noqa: E501
        :type links: List[Link]
        :param properties: The properties of this MatterResponse.  # noqa: E501
        :type properties: MatterProperties
        """
        self.swagger_types = {
            '_class': List[str],
            'actions': List[Action],
            'links': List[Link],
            'properties': MatterProperties
        }

        self.attribute_map = {
            '_class': 'class',
            'actions': 'actions',
            'links': 'links',
            'properties': 'properties'
        }
        self.__class = _class
        self._actions = actions
        self._links = links
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'MatterResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatterResponse of this MatterResponse.  # noqa: E501
        :rtype: MatterResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _class(self) -> List[str]:
        """Gets the _class of this MatterResponse.


        :return: The _class of this MatterResponse.
        :rtype: List[str]
        """
        return self.__class

    @_class.setter
    def _class(self, _class: List[str]):
        """Sets the _class of this MatterResponse.


        :param _class: The _class of this MatterResponse.
        :type _class: List[str]
        """

        self.__class = _class

    @property
    def actions(self) -> List[Action]:
        """Gets the actions of this MatterResponse.


        :return: The actions of this MatterResponse.
        :rtype: List[Action]
        """
        return self._actions

    @actions.setter
    def actions(self, actions: List[Action]):
        """Sets the actions of this MatterResponse.


        :param actions: The actions of this MatterResponse.
        :type actions: List[Action]
        """

        self._actions = actions

    @property
    def links(self) -> List[Link]:
        """Gets the links of this MatterResponse.


        :return: The links of this MatterResponse.
        :rtype: List[Link]
        """
        return self._links

    @links.setter
    def links(self, links: List[Link]):
        """Sets the links of this MatterResponse.


        :param links: The links of this MatterResponse.
        :type links: List[Link]
        """

        self._links = links

    @property
    def properties(self) -> MatterProperties:
        """Gets the properties of this MatterResponse.


        :return: The properties of this MatterResponse.
        :rtype: MatterProperties
        """
        return self._properties

    @properties.setter
    def properties(self, properties: MatterProperties):
        """Sets the properties of this MatterResponse.


        :param properties: The properties of this MatterResponse.
        :type properties: MatterProperties
        """

        self._properties = properties
