openapi: 3.0.2
info:
  title: API Title
  version: "1.0"
servers:
- url: https://api.server.test/v1
paths:
  /matter:
    post:
      tags:
      - FSM
      summary: Add a new State Machine to the pool
      operationId: add_matter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatterProperties'
      responses:
        "200":
          description: Matter object inserted
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.fsm_controller
  /matter/{matterId}:
    get:
      tags:
      - FSM
      summary: Info for a specific Matter object
      operationId: get_by_id
      parameters:
      - name: matterId
        in: path
        description: The id of the Matter object to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterResponse'
        "400":
          description: Invalid ID supplied
        "404":
          description: Matter object not found
      x-openapi-router-controller: swagger_server.controllers.fsm_controller
  /matter/{matterId}/melt:
    get:
      tags:
      - transitions
      summary: Trigger transition melt
      description: Advances the FSM
      operationId: do_melt
      parameters:
      - name: matterId
        in: path
        description: The id of the Matter object to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterResponse'
        "400":
          description: Invalid transition supplied
          content: {}
        "404":
          description: Transition not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.transitions_controller
  /matter/{matterId}/freez:
    get:
      tags:
      - transitions
      summary: Trigger transition freez
      description: Advances the FSM
      operationId: do_freez
      parameters:
      - name: matterId
        in: path
        description: The id of the Matter object to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterResponse'
        "400":
          description: Invalid transition supplied
          content: {}
        "404":
          description: Transition not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.transitions_controller
  /matter/{matterId}/evaporate:
    get:
      tags:
      - transitions
      summary: Trigger transition evaporate
      description: Advances the FSM
      operationId: do_evaporate
      parameters:
      - name: matterId
        in: path
        description: The id of the Matter object to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterResponse'
        "400":
          description: Invalid transition supplied
          content: {}
        "404":
          description: Transition not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.transitions_controller
  /matter/{matterId}/condensate:
    get:
      tags:
      - transitions
      summary: Trigger transition condensate
      description: Advances the FSM
      operationId: do_condensate
      parameters:
      - name: matterId
        in: path
        description: The id of the Matter object to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterResponse'
        "400":
          description: Invalid transition supplied
          content: {}
        "404":
          description: Transition not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.transitions_controller
  /matter/{matterId}/sublimate:
    get:
      tags:
      - transitions
      summary: Trigger transition sublimate
      description: Advances the FSM
      operationId: do_sublimate
      parameters:
      - name: matterId
        in: path
        description: The id of the Matter object to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterResponse'
        "400":
          description: Invalid transition supplied
          content: {}
        "404":
          description: Transition not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.transitions_controller
  /matter/{matterId}/deposit:
    get:
      tags:
      - transitions
      summary: Trigger transition deposit
      description: Advances the FSM
      operationId: do_deposit
      parameters:
      - name: matterId
        in: path
        description: The id of the Matter object to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterResponse'
        "400":
          description: Invalid transition supplied
          content: {}
        "404":
          description: Transition not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.transitions_controller
  /matter/{matterId}/ionize:
    get:
      tags:
      - transitions
      summary: Trigger transition ionize
      description: Advances the FSM
      operationId: do_ionize
      parameters:
      - name: matterId
        in: path
        description: The id of the Matter object to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterResponse'
        "400":
          description: Invalid transition supplied
          content: {}
        "404":
          description: Transition not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.transitions_controller
  /matter/{matterId}/deionize:
    get:
      tags:
      - transitions
      summary: Trigger transition deionize
      description: Advances the FSM
      operationId: do_deionize
      parameters:
      - name: matterId
        in: path
        description: The id of the Matter object to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatterResponse'
        "400":
          description: Invalid transition supplied
          content: {}
        "404":
          description: Transition not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.transitions_controller
components:
  schemas:
    MatterResponse:
      type: object
      allOf:
      - $ref: '#/components/schemas/Entity'
      - properties:
          properties:
            $ref: '#/components/schemas/MatterProperties'
    MatterProperties:
      required:
      - id
      - state
      type: object
      properties:
        id:
          type: string
        state:
          type: string
          enum:
          - solid
          - liquid
          - gas
          - plasma
        temperatur:
          type: number
      additionalProperties: false
    Entity:
      type: object
      properties:
        class:
          type: array
          items:
            type: string
        actions:
          type: array
          items:
            $ref: '#/components/schemas/Action'
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
    Action:
      required:
      - href
      - name
      type: object
      properties:
        class:
          type: array
          items:
            type: string
        name:
          type: string
        method:
          type: string
        href:
          type: string
        title:
          type: string
        type:
          type: string
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
    Field:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum:
          - hidden
          - text
          - search
          - tel
          - url
          - email
          - password
          - datetime
          - date
          - month
          - week
          - time
          - datetime-local
          - number
          - range
          - color
          - checkbox
          - radio
          - file
        title:
          type: string
        value:
          type: string
    Link:
      required:
      - href
      - rel
      type: object
      properties:
        class:
          type: array
          items:
            type: string
        title:
          type: string
        rel:
          type: array
          items:
            type: string
        href:
          type: string
        type:
          type: string

